<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Navigation' => 'Навигация',
    'Statistics' => 'Статистика',
    'A link to reset password will be sent there.' => 'Ссылка для сброса пароля будет отправлена на указаный email',
    'Alias' => 'ЧПУ',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Banners' => 'Баннеры',
    'Category' => 'Категория',
    'Clear' => 'Очистить',
    'Create' => 'Создать',
    'Create Banner' => 'Создать баннер',
    'Create News' => 'Создать новость',
    'Create Page' => 'Создать страницу',
    'Create User' => 'Создать пользователя',
    'Created At' => 'Создано',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Email' => 'Email',
    'ID' => 'ID',
    'If you forgot your password you can' => 'Если вы забыли пароль вы можете ',
    'Images' => 'Изображение',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль',
    'Level' => 'Уровень',
    'Link' => 'Ссылка',
    'Log Time' => 'Время события',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'Logs' => 'События',
    'Message' => 'Сообщение',
    'Meta Description' => 'Мета Описание',
    'Meta Title' => 'Мета Заголовок',
    'Name' => 'Имя',
    'News' => 'Новости',
    'Page Content' => 'Текст страницы',
    'Pages' => 'Страницы',
    'Partner' => 'Партнер',
    'Password' => 'Пароль',
    'Password reset' => 'Сбросить пароль',
    'Please fill out your email.' => 'Укажите ваш email',
    'Prefix' => 'Префикс',
    'Publish At' => 'Опубликованно',
    'Publish date' => 'Дата публикации',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Сбросить пароль',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Status' => 'Статус',
    'Summary' => 'Резюме',
    'Support' => 'Поддержка',
    'System' => 'Система',
    'System Logs' => 'Журнал событий',
    'Text' => 'Текст',
    'This email address has already been taken.' => 'Этот email адрес уже используется',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update Banner' => 'Обновить баннер',
    'Update News' => 'Обновить новость',
    'Update Page' => 'Обновить страницу',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'Updated At' => 'Обновлено',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
    'back to' => 'вернуться на ',
    'login page' => 'страницу авторизации',
    'reset it' => 'сбросить его',
];
