<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => 'Email',
    'Meta Description' => 'Мата Описание',
    'Meta Title' => 'Мета Заголовок',
    'Update Banner' => 'Обновить баннер',
    'Alias' => 'ЧПУ',
    'Banners' => 'Баннеры',
    'Create' => 'Создать',
    'Create Banner' => 'Создать баннер',
    'Create News' => 'Создать новость',
    'Create Page' => 'Создать страницу',
    'Create User' => 'Создать пользователя',
    'Created At' => 'Создано',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль',
    'News' => 'Новости',
    'Pages' => 'Страницы',
    'Publish At' => 'Опубликованно',
    'Publish date' => 'Дата публикации',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Status' => 'Статус',
    'Summary' => 'Резюме',
    'Text' => 'Текст',
    'This email address has already been taken.' => 'Этот email адрес уже используется',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update News' => 'Обновить новость',
    'Update Page' => 'Обновить страницу',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'Updated At' => 'Обновлено',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
];
